### ISSUE TITLE
Bad Substitution line 81.

### ISSUE THREAD

**Issue by uglygus** [eaut/rsync-time-backup#19] opened 2016-05-16 19:59 UTC
Bad Substitution line 81.

```
$./tmbackup.sh init ~/Dektop/orig
backup location: /Users/gary/Dektop/orig 
./tmbackup.sh: line 81: [${TYPE^^}]: bad substitution
Usage: tmbackup [OPTIONS] command [ARGS]
Try 'tmbackup --help' for more information.

```

OSX 10.10.5

```
$bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
Copyright (C) 2007 Free Software Foundation, Inc.
```

I honestly don't know enough BASH to understand the  double caret but removing the ^^ seemed to solve it and leave to other problems.
`[[ $TYPE == "info" ]] && echo "${MSG[@]}" || { MSG=("[${TYPE}]" "${MSG[@]}") ; echo "${MSG[@]}" 1>&2 ; }`

**Comment by eaut** [comment] 2016-05-16 20:18
The problem is once again that even the latest OSX has a very old bash version, 3.2.57 was released in 2007! The ${TYPE^^} substitution command was introduced with bash 4 and converts the variable to uppercase. 
The uppercase feature is really nothing crucial, but the fact that apple is not shipping a recent bash version is annoying.

**Comment by uglygus** [comment] 2016-05-16 20:36
Agreed. Very annoying. Thanks for the information.

**Comment by eaut** [comment] 2016-06-19 13:58
bash4 dependency removed with 196961963fa07d753a984b12a7036416a9ca03b8

**Closed as completed by eaut** 2016-06-19 13:58 UTC
